version: '2'
services:
  metrix:
    build: .
    volumes:
      - .:/home/rocket/
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: stompy
      POSTGRES_DB: metrix
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: stompy
      POSTGRES_DB: metrix
